# STS role and target account
Sts.Role: arn:aws:iam::360825983472:role/admin

# Stack settings
Stack.Name: microtrader-development
Stack.Description: Microtrader Stack - Development

# Override all deletion policies of type AWS::RDS::DBInstance
AWS::RDS::DBInstance:
  DeletionPolicy: Delete

# Override all deletion policies of type AWS::Logs::LogGroup
AWS::Logs::LogGroup:
  DeletionPolicy: Delete

# Microtrader settings
Stack.Inputs.MicrotraderQuoteHttpPort: 8000
Stack.Inputs.MicrotraderAuditHttpPort: 8001
Stack.Inputs.MicrotraderDashboardHttpPort: 8002

# Database settings
Stack.Inputs.DatabaseName: audit
Stack.Inputs.DatabaseUsername: audit
Stack.Inputs.DatabasePassword: AQICAHg+MFRemoo/sKxKdEq2wb0a3t8ka2R7/PlsB7DAGKoMCwF7Dd+bDG2S4WQi0QCGAOIVAAAAczBxBgkqhkiG9w0BBwagZDBiAgEAMF0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMK+pOfsCS9p7xCckDAgEQgDCxMNxAw8glR93fuKP41z2ZR5+r+V3sbilk+AJwCkIBsAYeTntLEIbKeUEDUe2VzCE=

# Application settings
Stack.Inputs.ApplicationDnsName: dev-microtrader
Stack.Inputs.ApplicationImageId: ami-0952b5db8f4f94ea3
Stack.Inputs.ApplicationKeyName: microtrader

# ECS task runner settings
Stack.Inputs.EcsTaskRunnerVersion: SsyPLbuaxHy23zsu7Y38bqrBz_5bnbM0
